# Generated by Django 2.2.1 on 2021-04-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='cyclic',
            field=models.BooleanField(default=False),
        ),
    ]
