# Generated by Django 2.2.1 on 2021-04-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemer', '0002_auto_20210413_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='done',
        ),
        migrations.AddField(
            model_name='task',
            name='cyclic_on',
            field=models.CharField(choices=[('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year')], default='day', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
