# Generated by Django 2.2.1 on 2021-04-13 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schemer', '0003_auto_20210413_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='cyclic',
        ),
        migrations.AlterField(
            model_name='task',
            name='cyclic_on',
            field=models.CharField(blank=True, choices=[('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
