# Generated by Django 2.2.1 on 2021-04-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemer', '0006_auto_20210413_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='day',
        ),
        migrations.RemoveField(
            model_name='task',
            name='month',
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
