# Generated by Django 2.2.1 on 2021-04-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemer', '0009_auto_20210414_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='option',
            field=models.IntegerField(default=0),
        ),
    ]
