# Generated by Django 2.2.1 on 2021-04-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemer', '0010_task_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='interval',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='cyclic_on',
            field=models.CharField(blank=True, choices=[('second', 'second'), ('minute', 'minute'), ('hour', 'hour'), ('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year')], max_length=10, null=True),
        ),
    ]
