# Generated by Django 2.2.1 on 2021-05-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemer', '0012_auto_20210428_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dependencies',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FilePathField(default=None, match='^.*\\.(bat|py)$', path='C:/Users/timot/Documents/schedulerService/scripts/'),
        ),
    ]
