# Generated by Django 2.2.1 on 2021-05-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemer', '0013_auto_20210511_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='dependencies',
        ),
        migrations.AddField(
            model_name='task',
            name='dependency',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
