# Generated by Django 2.2.1 on 2021-05-12 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemer', '0014_auto_20210512_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='interval',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
