# Generated by Django 2.2.1 on 2021-05-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemer', '0015_auto_20210512_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dependency',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
