# Generated by Django 2.2.1 on 2021-06-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemer', '0019_task_is_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='satisfaction_pattern',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.IntegerField(default=-1),
        ),
    ]
