# Generated by Django 2.2.1 on 2021-06-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemer', '0020_auto_20210601_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
